apiVersion: v1
kind: ResourceQuota
metadata:
  name: trainxops-quota
  namespace: trainxops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "5"
    persistentvolumeclaims: "3"
    requests.storage: "20Gi"
    services: "5"
    configmaps: "10"
    secrets: "10"
    replicationcontrollers: "5"
#ResourceQuota prevents a single namespace from consuming all cluster resources, which is essential in shared clusters
